# Generated by Django 5.1.7 on 2025-04-09 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_category_project_is_accepted_alter_project_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(default='images/default_thumbnail.jpg', upload_to='images/'),
        ),
    ]
